### ISSUE TITLE
README.MD Suggestion

### ISSUE THREAD

**Issue by simonprovost** [Richard-DEPIERRE/MUL_my_rpg_2019#1]
**Hey guys,**

I see your project by chance, I noted that it's a cross platform game, well done :+1: . But I have a question, most of the project on github have their "README.MD" fully in English. Why? Probably because people of some nations learn English as an international speaking language. Thus, in order to target more people than only french peoples I suggest you to translate it, isn't it ?

Simon.

**Comment by Richard-DEPIERRE** [comment]
Hey Simon,

Thank you very much for your suggestion, we are going to update the README.md to be in English since I do agree with you. 

Thank you very much !
Richard.
